spring.application.name=worldCup

spring.datasource.url=jdbc:oracle:thin:@192.168.1.100:1521:xe
spring.datasource.username=c##test
spring.datasource.password=test
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# HibernateDB Table AutoMatical
spring.jpa.hibernate.ddl-auto=update

#Log
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.itbank.worldcup=DEBUG
logging.level.org.springframework.web=DEBUG

mybatis.mapper-locations=classpath:mybatis/**/*-mapper.xml
mybatis.config-location=classpath:mybatis/config.xml

logging.level.com.zaxxer.hikari=DEBUG

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.extras.springsecurity.enabled=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


file.upload.categoryDir=C:/upload/worldcup/categoryImg
file.upload.itemsDir=C:/upload/worldcup/items
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n